# Generated by Django 3.2.20 on 2023-07-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_list', '0002_alter_todo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
