# Generated by Django 3.2.20 on 2023-07-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_list', '0003_remove_todo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_on',
        ),
    ]
